[2024-04-26T00:08:50.238+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T00:08:50.262+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.test_alert manual__2024-04-26T00:08:34.050008+00:00 [queued]>
[2024-04-26T00:08:50.390+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.test_alert manual__2024-04-26T00:08:34.050008+00:00 [queued]>
[2024-04-26T00:08:50.390+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-26T00:08:50.399+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): test_alert> on 2024-04-26 00:08:34.050008+00:00
[2024-04-26T00:08:50.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6586) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T00:08:50.408+0000] {standard_task_runner.py:63} INFO - Started process 6588 to run task
[2024-04-26T00:08:50.408+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'test_alert', 'manual__2024-04-26T00:08:34.050008+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpw_3o9lg8']
[2024-04-26T00:08:50.409+0000] {standard_task_runner.py:91} INFO - Job 273: Subtask test_alert
[2024-04-26T00:08:50.442+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.test_alert manual__2024-04-26T00:08:34.050008+00:00 [running]> on host cf1d83d83b27
[2024-04-26T00:08:50.500+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='test_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-04-26T00:08:34.050008+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-26T00:08:34.050008+00:00'
[2024-04-26T00:08:50.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T00:08:50.529+0000] {logging_mixin.py:188} INFO - Hay un problema
[2024-04-26T00:08:50.529+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T00:08:50.529+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T00:08:50.535+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=test_alert, execution_date=20240426T000834, start_date=20240426T000850, end_date=20240426T000850
[2024-04-26T00:08:50.582+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T00:08:50.594+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T00:08:50.596+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
