[2024-04-26T17:26:09.418+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T17:26:09.446+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.send_air_quality_alerts backfill__2024-04-05T22:00:00+00:00 [queued]>
[2024-04-26T17:26:09.452+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.send_air_quality_alerts backfill__2024-04-05T22:00:00+00:00 [queued]>
[2024-04-26T17:26:09.453+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T17:26:09.462+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_air_quality_alerts> on 2024-04-05 22:00:00+00:00
[2024-04-26T17:26:09.472+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=915) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T17:26:09.472+0000] {standard_task_runner.py:63} INFO - Started process 918 to run task
[2024-04-26T17:26:09.472+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'send_air_quality_alerts', 'backfill__2024-04-05T22:00:00+00:00', '--job-id', '353', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmp8sow9biq']
[2024-04-26T17:26:09.473+0000] {standard_task_runner.py:91} INFO - Job 353: Subtask send_air_quality_alerts
[2024-04-26T17:26:09.507+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.send_air_quality_alerts backfill__2024-04-05T22:00:00+00:00 [running]> on host 4718ecf2379c
[2024-04-26T17:26:09.567+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='send_air_quality_alerts' AIRFLOW_CTX_EXECUTION_DATE='2024-04-05T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-04-05T22:00:00+00:00'
[2024-04-26T17:26:09.567+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T17:26:09.576+0000] {tasks.py:94} INFO - Generating air quality alerts...
[2024-04-26T17:26:09.577+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T17:26:09.578+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 95, in send_air_quality_alerts
    alert_message = air_quality_alerts()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/air_quality_alerts.py", line 68, in air_quality_alerts
    data = pd.read_csv("air_quality_data.csv")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'air_quality_data.csv'
[2024-04-26T17:26:09.587+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality_pipeline, task_id=send_air_quality_alerts, execution_date=20240405T220000, start_date=20240426T172609, end_date=20240426T172609
[2024-04-26T17:26:09.594+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 353 for task send_air_quality_alerts ([Errno 2] No such file or directory: 'air_quality_data.csv'; 918)
[2024-04-26T17:26:09.605+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T17:26:09.621+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T17:26:09.622+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-26T17:45:45.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T17:45:45.435+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.send_air_quality_alerts backfill__2024-04-05T22:00:00+00:00 [queued]>
[2024-04-26T17:45:45.440+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.send_air_quality_alerts backfill__2024-04-05T22:00:00+00:00 [queued]>
[2024-04-26T17:45:45.441+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T17:45:45.449+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_air_quality_alerts> on 2024-04-05 22:00:00+00:00
[2024-04-26T17:45:45.457+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1882) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T17:45:45.458+0000] {standard_task_runner.py:63} INFO - Started process 1883 to run task
[2024-04-26T17:45:45.458+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'send_air_quality_alerts', 'backfill__2024-04-05T22:00:00+00:00', '--job-id', '411', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmphfp8kklb']
[2024-04-26T17:45:45.459+0000] {standard_task_runner.py:91} INFO - Job 411: Subtask send_air_quality_alerts
[2024-04-26T17:45:45.492+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.send_air_quality_alerts backfill__2024-04-05T22:00:00+00:00 [running]> on host 4718ecf2379c
[2024-04-26T17:45:45.555+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='send_air_quality_alerts' AIRFLOW_CTX_EXECUTION_DATE='2024-04-05T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-04-05T22:00:00+00:00'
[2024-04-26T17:45:45.555+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T17:45:45.564+0000] {tasks.py:94} INFO - Generating air quality alerts...
[2024-04-26T17:45:45.572+0000] {tasks.py:97} INFO - Sending air quality alerts via email...
[2024-04-26T17:45:46.604+0000] {tasks.py:99} INFO - Air quality alerts sent via email.
[2024-04-26T17:45:46.605+0000] {tasks.py:102} INFO - Cleaning up temporary files...
[2024-04-26T17:45:46.606+0000] {tasks.py:105} INFO - Temporary files cleaned up.
[2024-04-26T17:45:46.606+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T17:45:46.606+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T17:45:46.615+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=air_quality_pipeline, task_id=send_air_quality_alerts, execution_date=20240405T220000, start_date=20240426T174545, end_date=20240426T174546
[2024-04-26T17:45:46.673+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T17:45:46.686+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T17:45:46.688+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
